# This file has been autogenerated by the pywayland scanner

# Copyright © 2022 Vaxry
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

from __future__ import annotations

import enum

from pywayland.protocol_core import Argument, ArgumentType, Global, Interface, Proxy, Resource


class HyprlandGlobalShortcutV1(Interface):
    """A shortcut

    This object represents a single shortcut.
    """

    name = "hyprland_global_shortcut_v1"
    version = 1


class HyprlandGlobalShortcutsManagerV1(Interface):
    """Manager to register global shortcuts

    This object is a manager which offers requests to create global shortcuts.
    """

    name = "hyprland_global_shortcuts_manager_v1"
    version = 1

    class error(enum.IntEnum):
        already_taken = 0


class HyprlandGlobalShortcutV1Resource(Resource[HyprlandGlobalShortcutV1]):
    interface = HyprlandGlobalShortcutV1

    @HyprlandGlobalShortcutV1.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
    )
    def pressed(self, tv_sec_hi: int, tv_sec_lo: int, tv_nsec: int) -> None:
        """Keystroke pressed

        The keystroke was pressed.

        tv_ values hold the timestamp of the occurrence.

        :param tv_sec_hi:
            high 32 bits of the seconds part of the timestamp
        :type tv_sec_hi:
            `ArgumentType.Uint`
        :param tv_sec_lo:
            low 32 bits of the seconds part of the timestamp
        :type tv_sec_lo:
            `ArgumentType.Uint`
        :param tv_nsec:
            nanoseconds part of the timestamp
        :type tv_nsec:
            `ArgumentType.Uint`
        """
        self._post_event(0, tv_sec_hi, tv_sec_lo, tv_nsec)

    @HyprlandGlobalShortcutV1.event(
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
        Argument(ArgumentType.Uint),
    )
    def released(self, tv_sec_hi: int, tv_sec_lo: int, tv_nsec: int) -> None:
        """Keystroke released

        The keystroke was released.

        tv_ values hold the timestamp of the occurrence.

        :param tv_sec_hi:
            high 32 bits of the seconds part of the timestamp
        :type tv_sec_hi:
            `ArgumentType.Uint`
        :param tv_sec_lo:
            low 32 bits of the seconds part of the timestamp
        :type tv_sec_lo:
            `ArgumentType.Uint`
        :param tv_nsec:
            nanoseconds part of the timestamp
        :type tv_nsec:
            `ArgumentType.Uint`
        """
        self._post_event(1, tv_sec_hi, tv_sec_lo, tv_nsec)


class HyprlandGlobalShortcutsManagerV1Resource(Resource[HyprlandGlobalShortcutsManagerV1]):
    interface = HyprlandGlobalShortcutsManagerV1


class HyprlandGlobalShortcutV1Proxy(Proxy[HyprlandGlobalShortcutV1]):
    interface = HyprlandGlobalShortcutV1

    @HyprlandGlobalShortcutV1.request()
    def destroy(self) -> None:
        """Delete this object, used or not

        Destroys the shortcut. Can be sent at any time by the client.
        """
        self._marshal(0)
        self._destroy()


class HyprlandGlobalShortcutsManagerV1Proxy(Proxy[HyprlandGlobalShortcutsManagerV1]):
    interface = HyprlandGlobalShortcutsManagerV1

    @HyprlandGlobalShortcutsManagerV1.request(
        Argument(ArgumentType.NewId, interface=HyprlandGlobalShortcutV1),
        Argument(ArgumentType.String),
        Argument(ArgumentType.String),
        Argument(ArgumentType.String),
        Argument(ArgumentType.String),
    )
    def register_shortcut(self, id: str, app_id: str, description: str, trigger_description: str) -> HyprlandGlobalShortcutV1Proxy:
        """Register a shortcut

        Register a new global shortcut.

        A global shortcut is anonymous, meaning the app does not know what
        key(s) trigger it.

        The shortcut's keybinding shall be dealt with by the compositor.

        In the case of a duplicate app_id + id combination, the already_taken
        protocol error is raised.

        :param id:
            a unique id for the shortcut
        :type id:
            `ArgumentType.String`
        :param app_id:
            the app_id of the application requesting the shortcut
        :type app_id:
            `ArgumentType.String`
        :param description:
            user-readable text describing what the shortcut does.
        :type description:
            `ArgumentType.String`
        :param trigger_description:
            user-readable text describing how to trigger the shortcut for the
            client to render.
        :type trigger_description:
            `ArgumentType.String`
        :returns:
            :class:`~pywayland.protocol.hyprland_global_shortcuts_v1.HyprlandGlobalShortcutV1`
        """
        shortcut = self._marshal_constructor(0, HyprlandGlobalShortcutV1, id, app_id, description, trigger_description)
        return shortcut

    @HyprlandGlobalShortcutsManagerV1.request()
    def destroy(self) -> None:
        """Destroy the manager

        All objects created by the manager will still remain valid, until their
        appropriate destroy request has been called.
        """
        self._marshal(1)
        self._destroy()


class HyprlandGlobalShortcutV1Global(Global[HyprlandGlobalShortcutV1]):
    interface = HyprlandGlobalShortcutV1


class HyprlandGlobalShortcutsManagerV1Global(Global[HyprlandGlobalShortcutsManagerV1]):
    interface = HyprlandGlobalShortcutsManagerV1


HyprlandGlobalShortcutV1._gen_c()
HyprlandGlobalShortcutV1.proxy_class = HyprlandGlobalShortcutV1Proxy
HyprlandGlobalShortcutV1.resource_class = HyprlandGlobalShortcutV1Resource
HyprlandGlobalShortcutV1.global_class = HyprlandGlobalShortcutV1Global


HyprlandGlobalShortcutsManagerV1._gen_c()
HyprlandGlobalShortcutsManagerV1.proxy_class = HyprlandGlobalShortcutsManagerV1Proxy
HyprlandGlobalShortcutsManagerV1.resource_class = HyprlandGlobalShortcutsManagerV1Resource
HyprlandGlobalShortcutsManagerV1.global_class = HyprlandGlobalShortcutsManagerV1Global
